ProjectMVC/Models/AnuncioWebmotors.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectMVC.Models
{
    public class AnuncioWebmotors
    {
        [DisplayName("#")]
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "Por favor, informe a Marca")]
        [DisplayName("Marca")]
        [StringLength(45, ErrorMessage = "A Marca deve conter até 45 caracteres")]
        public string marca { get; set; }
        [Required(ErrorMessage = "Por favor, informe o Modelo")]
        [DisplayName("Modelo")]
        [StringLength(45, ErrorMessage = "A Modelo deve conter até 45 caracteres")]
        public string modelo { get; set; }
        [Required(ErrorMessage = "Por favor, informe a Versão")]
        [DisplayName("Versão")]
        [StringLength(45, ErrorMessage = "A Versão deve conter até 45 caracteres")]
        public string versao { get; set; }
        [Required(ErrorMessage = "Por favor, informe o Ano de Fabricação")]
        [DisplayName("Ano")]
        public int ano { get; set; }
        [Required(ErrorMessage = "Por favor, informe a Quilometragem")]
        [DisplayName("Quilometragem")]
        public int quilometragem { get; set; }
        [Required(ErrorMessage = "Por favor, informe a Observação")]
        [DisplayName("Observação")]
        public string observacao { get; set; }
    }
}

ProjectMVC/Models/ErrorViewModel.cs
using System;

namespace ProjectMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjectMVC/Controllers/AnuncioWebmotorsController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectMVC.Data.Context;
using ProjectMVC.Models;
using X.PagedList;
using System.Text.RegularExpressions;

namespace ProjectMVC.Controllers
{
    public class AnuncioWebmotorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnuncioWebmotorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AnuncioWebmotors
        public async Task<IActionResult> Index(string marca, string modelo, string versao, int pag = 1)
        {
            var db = _context.AnuncioWebmotors.AsNoTracking();

            if (!string.IsNullOrEmpty(marca))
            { db = db.Where(c => c.marca == marca); }

            if (!string.IsNullOrEmpty(modelo))
            { db = db.Where(c => c.modelo == modelo); }

            if (!string.IsNullOrEmpty(versao))
            { db = db.Where(c => c.versao == versao); }

            return View(await db?.OrderBy(am => am.ID).ToPagedListAsync(pag, 10));
        }

        // GET: AnuncioWebmotors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anuncioWebmotors = await _context.AnuncioWebmotors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (anuncioWebmotors == null)
            {
                return NotFound();
            }

            return View(anuncioWebmotors);
        }

        // GET: AnuncioWebmotors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AnuncioWebmotors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,marca,modelo,versao,ano,quilometragem,observacao")] AnuncioWebmotors anuncioWebmotors)
        {
            if (ModelState.IsValid)
            {
                _context.Add(anuncioWebmotors);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(anuncioWebmotors);
        }

        // GET: AnuncioWebmotors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anuncioWebmotors = await _context.AnuncioWebmotors.FindAsync(id);
            if (anuncioWebmotors == null)
            {
                return NotFound();
            }
            return View(anuncioWebmotors);
        }

        // POST: AnuncioWebmotors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,marca,modelo,versao,ano,quilometragem,observacao")] AnuncioWebmotors anuncioWebmotors)
        {
            if (id != anuncioWebmotors.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(anuncioWebmotors);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnuncioWebmotorsExists(anuncioWebmotors.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(anuncioWebmotors);
        }

        // GET: AnuncioWebmotors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anuncioWebmotors = await _context.AnuncioWebmotors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (anuncioWebmotors == null)
            {
                return NotFound();
            }

            return View(anuncioWebmotors);
        }

        // POST: AnuncioWebmotors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var anuncioWebmotors = await _context.AnuncioWebmotors.FindAsync(id);
            _context.AnuncioWebmotors.Remove(anuncioWebmotors);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnuncioWebmotorsExists(int id)
        {
            return _context.AnuncioWebmotors.Any(e => e.ID == id);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectMVC/Views/AnuncioWebmotors/Create.cshtml
@model ProjectMVC.Models.AnuncioWebmotors

@{
    ViewData["Title"] = "Create";
}

<h1>Novo Cadastro</h1>

<h4>Anuncio Webmotors</h4>
<hr />
<div class="row">
    <div class="col-md-7">
        @using (Html.BeginForm())
        {
            <div class="form-group">
                @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
                        @Html.HiddenFor(c => c.marca)
                        <select id="selMarca" class="form-control" onchange="ChangeMake(this);">
                            <option value="0">Selecione um modelo</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.modelo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.ValidationMessageFor(model => model.modelo, "", new { @class = "text-danger" })
                        @Html.HiddenFor(c => c.modelo)
                        <select id="selModelo" class="form-control" onchange="ChangeModel(this);">
                            <option value="0">Selecione um modelo</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    @Html.LabelFor(model => model.versao, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="checkbox">
                        @Html.ValidationMessageFor(model => model.versao, "", new { @class = "text-danger" })
                        @Html.HiddenFor(c => c.versao)
                        <select id="selVersao" class="form-control" onchange="ChangeVersion(this);">
                            <option value="0">Selecione uma Versao</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ano, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.ValidationMessageFor(model => model.ano, "", new { @class = "text-danger" })
                        @Html.TextBoxFor(model => model.ano)
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.quilometragem, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.ValidationMessageFor(model => model.quilometragem, "", new { @class = "text-danger" })
                        @Html.TextBoxFor(model => model.quilometragem)
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.observacao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.ValidationMessageFor(model => model.observacao, "", new { @class = "text-danger" })
                        @Html.TextBoxFor(model => model.observacao)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-light">Voltar</a>
</div>
<script src="~/js/site.js" asp-append-version="true"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectMVC/Views/AnuncioWebmotors/Delete.cshtml
@model ProjectMVC.Models.AnuncioWebmotors

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Voce deseja realmente excluir esse cadastro?</h3>
<div>
    <h4>Anuncio Webmotors</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.versao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.versao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ano)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.quilometragem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.quilometragem)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-light">Voltar</a>
    </form>
</div>

ProjectMVC/Views/AnuncioWebmotors/Details.cshtml
@model ProjectMVC.Models.AnuncioWebmotors

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Anuncio Webmotors</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.versao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.versao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ano)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.quilometragem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.quilometragem)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-warning">Editar</a>
    <a asp-action="Index" class="btn btn-light">Voltar</a>
</div>

ProjectMVC/Views/AnuncioWebmotors/Edit.cshtml
@model ProjectMVC.Models.AnuncioWebmotors

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Cadastro</h1>

<h4>Anuncio Webmotors</h4>
<hr />

<div class="row">
    <div class="col-md-7">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(c => c.ID)
            <div class="form-group">
                @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
                        @Html.HiddenFor(c => c.marca)
                        <select id="selMarca" class="form-control" onchange="ChangeMake(this);">
                            <option value="0">Selecione um modelo</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.modelo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.ValidationMessageFor(model => model.modelo, "", new { @class = "text-danger" })
                        @Html.HiddenFor(c => c.modelo)
                        <select id="selModelo" class="form-control" onchange="ChangeModel(this);">
                            <option value="0">Selecione um modelo</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    @Html.LabelFor(model => model.versao, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="checkbox">
                        @Html.ValidationMessageFor(model => model.versao, "", new { @class = "text-danger" })
                        @Html.HiddenFor(c => c.versao)
                        <select id="selVersao" class="form-control" onchange="ChangeVersion(this);">
                            <option value="0">Selecione uma Versao</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ano, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.ValidationMessageFor(model => model.ano, "", new { @class = "text-danger" })
                        @Html.TextBoxFor(model => model.ano)
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.quilometragem, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.ValidationMessageFor(model => model.quilometragem, "", new { @class = "text-danger" })
                        @Html.TextBoxFor(model => model.quilometragem)
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.observacao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.ValidationMessageFor(model => model.observacao, "", new { @class = "text-danger" })
                        @Html.TextBoxFor(model => model.observacao)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-light">Voltar</a>
</div>
<script src="~/js/site.js" asp-append-version="true"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectMVC/Views/AnuncioWebmotors/Index.cshtml
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<ProjectMVC.Models.AnuncioWebmotors>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm())
        {
            <div class="form-group form-inline">
                <div class="col-md-3">
                    <div class="checkbox">
                        @Html.Hidden("marca")
                        <select id="selMarca" class="form-control" onchange="ChangeMake(this);">
                            <option value="0">Selecione um modelo</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="checkbox">
                        @Html.Hidden("modelo")
                        <select id="selModelo" class="form-control" onchange="ChangeModel(this);">
                            <option value="0">Selecione um modelo</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <div class="checkbox">
                            @Html.Hidden("versao")
                            <select id="selVersao" class="form-control" onchange="ChangeVersion(this);">
                                <option value="0">Selecione uma Versao</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Procurar" class="btn btn-outline-success" />
            </div>
        }
    </div>
</div>
<p>
    <a asp-action="Create" class="btn btn-primary">Adicionar</a>
</p>
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().ID)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().marca)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().modelo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().versao)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().ano)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().quilometragem)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.marca)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.modelo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.versao)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ano)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.quilometragem)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.ID" class="btn btn-warning">Editar</a>
                            <a asp-action="Details" asp-route-id="@item.ID" class="btn btn-info">Detalhes</a>
                            <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div>
    <div style="float: right">
        Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
    </div>

    <div class="justify-content-center">
        @Html.PagedListPager(Model, pag => Url.Action("Index", new { pag }),
       new X.PagedList.Web.Common.PagedListRenderOptions
       {
           FunctionToTransformEachPageLink = (liTag, aTag) =>
           {
               aTag.Attributes.Add("class", "page-link".ToString());
               return aTag;
           },
           LiElementClasses = new[]
           {
               "page-item"
           },
           UlElementClasses = new[]
           {
               "pagination  justify-content-left"
           }
            })
    </div>
</div>
<script src="~/js/site.js" asp-append-version="true"></script>

ProjectMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="AnuncioWebmotors" asp-action="Index">ProjectMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ProjectMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>